### ISSUE TITLE
SDG 15.3.1 Download Map as TIFS IN SEPAL error 

### ISSUE THREAD

**Issue by sszzpruebas** [sepal-contrib/sdg_15.3.1#131]
Hi Sepal Team! 
I'm testing the SDG 15.3.1 Indicator using SEPAL and GEE connection. I can download zonal statistics data from SEPAL but when I'm trying to download Maps as TIFS, this error  appear : 
<img width="450" alt="image" src="https://github.com/sepal-contrib/sdg_15.3.1/assets/156904858/c5b8c900-5c47-4aab-89e9-fa7b2ea047b4">

How can i solve it ?,
Thank you in advance, 
Best regards,

Sylwer

**Comment by dfguerrerom** [comment]
This error might be related with the one you reported on https://github.com/sepal-contrib/sepal_mgci/issues/57, can you please confirm you have followed the steps to connect GEE and SEPAL that are documented here: https://docs.sepal.io/en/latest/setup/gee.html#connect-gee-and-sepal ?

**Comment by sszzpruebas** [comment]
Hi ! :) 
Yes i followed it and also this one https://docs.sepal.io/en/latest/modules/dwn/sdg_indicator.html.
I have the connection with GEE , i do it before run the SDG Indicator. 
![image](https://github.com/sepal-contrib/sdg_15.3.1/assets/156904858/e94146e8-ebd2-47c1-a25b-5b2da0297dc6)

Actually, when I run the SDG Indicator i choose an AOI from GEE Asset. 

![image](https://github.com/sepal-contrib/sdg_15.3.1/assets/156904858/3b81d3bc-2bfa-478c-94bf-67fa92c3e235)

All indicators runs well: 
![image](https://github.com/sepal-contrib/sdg_15.3.1/assets/156904858/d75e8c2b-345f-4f82-81c0-3cccd867c117)

Neverthless when i try to download results, the following error appears: 

![image](https://github.com/sepal-contrib/sdg_15.3.1/assets/156904858/4c5a0551-997b-42a2-85fa-95267147d55f)

Thank you in advance, 
Best regards, 

Sylwer
